name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Azure Marketplace Generator ${{ github.ref }}
        body: |
          Azure Marketplace Generator Release
          
          ## Changes
          - Core engine for Azure managed applications
          - Storage solution templates
          - ARM-TTK validation integration
          
          ## Installation
          ```bash
          npm install -g @hoiltd/azure-marketplace-generator
          npm run install-arm-ttk
          ```
        draft: false
        prerelease: false