name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup ARM-TTK for testing
      run: |
        echo "🛡️ Setting up ARM-TTK for validation tests..."
        # Install PowerShell if not available
        sudo apt-get update
        sudo apt-get install -y powershell
        # Clone ARM-TTK from official Microsoft repository
        git clone https://github.com/Azure/arm-ttk.git /tmp/arm-ttk
        # Create symlink for tests to find ARM-TTK at expected location
        sudo ln -sf /tmp/arm-ttk /home/runner/work/azure-marketplace-generator/azure-marketplace-generator/arm-ttk

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Run custom security scan
      run: npm run test:security

    - name: Build and test
      run: |
        npm run build
        npm run test:ci

    - name: Validate CLI functionality
      run: |
        node dist/cli/index.js --help
        node dist/cli/index.js validate --help
        node dist/cli/index.js deploy --help

  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Dependency Review
      uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a
      with:
        fail-on-severity: moderate