name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate

    - name: Run custom security scan
      run: npm run test:security

    - name: Run Snyk security scan
      uses: snyk/actions/node@9adf32b1121593767fc3c057af55b55db032dc04
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=medium

    - name: Upload security scan results
      uses: github/codeql-action/upload-sarif@04df1262e6247151b5ac09cd2c303ac36ad3f62b
      if: always()
      with:
        sarif_file: security-results.sarif
      continue-on-error: true

    - name: Build and test
      run: |
        npm run build
        npm test

    - name: Validate CLI functionality
      run: |
        node dist/cli/index.js --help
        node dist/cli/index.js validate --help
        node dist/cli/index.js deploy --help

  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    if: github.event_name == 'pull_request'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c
      with:
        fail-on-severity: moderate